### ISSUE TITLE
Handle duplicate imports while parsing

### ISSUE THREAD

**Issue by Fxhnd** [thahmann/macleod#11]
At the current moment the Parser works overtime because no effort is made to reuse already tokenized/parsed files. Speed-wise it's still faster than the previous implementation (can tokenize/parse/import all of voids_extended.clif in under 8 seconds with output) even with the multitude of duplicate imports.

Don't know the exact way forward here, but marking it down so we're aware.

**Comment by thahmann** [comment]
Believe it is fixed with the latest updated to Ontology.resolve_imports()
