### ISSUE TITLE
Allow bin/ programs to work regardless of current directory

### ISSUE THREAD

**Issue by Fxhnd** [thahmann/macleod#16]
Somewhere, somehow, the path management for resolving files related to the old tasks is still all wonky. If you want to run bin/check_consistency.py you'll need to actually be in the top level of the qs/ directory (e.g. You command has to look like: 

`python3 /path/to/macleod/bin/check_consistency.py multidim_space_codi/codi.clif`

This should go away while porting the tasks to the new object structure. But that doesn't have a defined timeline so this is here as a sort of, "How do I?"

**Comment by thahmann** [comment]
I believe this is taken care of, at least it works as long as the full path to the task is specified.
