### ISSUE TITLE
Consolidate distinction between constants and variables

### ISSUE THREAD

**Issue by thahmann** [thahmann/macleod#21]
in the editor, use the functionality for finding constants from the "ontology object" in the object structure (implemented by @Fxhnd in the DL branch)

**Comment by evanmrsampson** [comment]
@Fxhnd how is a constant stored? Basically right now to get variables I'm doing a dfs, and getting the variables from the predicates and functions. Those are just stored as strings though, so I'm not sure how to differentiate easily.

The solution I thought of was to look at the quantified variables in the axiom. If the variable is not in the list of quantified variables, it must be a constant.

Let me know what you think!

**Comment by thahmann** [comment]
If I'm not mistaken, Rob already added constants to the functions. They are
just 0-ary functions. I just don't want to have to places that calculate
the constants.

**Comment by Fxhnd** [comment]
@evanmrsampson your method of finding constants is correct. I added a bunch of utility methods to the Axiom class, one of which is the `.constants()` method which return the list of constants. There are similar methods for getting quantifiers, predicates, functions, and etc.

They can be found in the commit [here](https://github.com/thahmann/macleod/commit/9a0c5888aa1b27004cd5c5776a939b0a3f1d164c).

**Comment by evanmrsampson** [comment]
Added in commit 1183c64d5d59a140358154ed72e7be9a275083c8
