### ISSUE TITLE
Parser.py doesn't support "if ... then"

### ISSUE THREAD

**Issue by evanmrsampson** [thahmann/macleod#24]
Parser.py doesn't support "if X then Y", instead it does "if X Y", where X and Y are axioms. @thahmann said in an email that it SHOULD be "if X then Y" and to throw an error otherwise. However, a lot of things in that email aren't the case anymore.

Just looking to get some guidance before I change anything.

**Comment by thahmann** [comment]
(iff X Y) is needed.  
I wasn't aware that the draft uses (implies X Y) rather than (if X Y).
I think we need to support (implies X Y) as well.

**Comment by Fxhnd** [comment]
My update may not have made it in time. It looks like the (implies X Y)
syntax was scrapped in favor of the "if" form.

**Comment by thahmann** [comment]
Ok, then all is good.
