### ISSUE TITLE
bad magic number in 'macleod': b'\x03\xf3\r\n': ImportError

### ISSUE THREAD

**Issue by carmenchui** [thahmann/macleod#30]
After synchronizing this commit @thahmann@caae8b586a897a9b92079a2b0264167f5ae9ebb5 , I came across this error in the OS X Terminal:
`bad magic number in 'macleod': b'\x03\xf3\r\n': ImportError
`

It can be fixed by deleting the Python cache for the macleod directory:
`find . -name \*.pyc -delete
`

Not sure if this is worth including in the README or the installation instructions if others come across this error while running macleod.

**Comment by thahmann** [comment]
This sounds strange. I added it to the README in case anyone comes across it.
Thanks for finding a solution!
