### ISSUE TITLE
AttributeError: module 'macleod.Filemgt' has no attribute 'config_file'

### ISSUE THREAD

**Issue by carmenchui** [thahmann/macleod#33]
Hi Torsten,

I noticed you've made some changes to macleod -- I actually have a new MacBook and was trying to install the latest version of macleod on this new computer.

I came across this error message:

`Traceback (most recent call last):
  File "gui_beta/gui_main.py", line 284, in <module>
    window = MacleodWindow()
  File "gui_beta/gui_main.py", line 40, in __init__
    self.setup_widgets()
  File "gui_beta/gui_main.py", line 45, in setup_widgets
    self.editor_pane = gui_widgets.TabController(self, self.ontologies)
  File "/Users/cchui/Documents/GitHub/macleod/macleod/gui/gui_beta/gui_widgets.py", line 16, in __init__
    self.add_file()
  File "/Users/cchui/Documents/GitHub/macleod/macleod/gui/gui_beta/gui_widgets.py", line 32, in add_file
    gui_highlighter.CLIFSyntaxHighlighter(new_tab, None, None)
  File "/Users/cchui/Documents/GitHub/macleod/macleod/gui/gui_beta/gui_highlighter.py", line 24, in __init__
    self.format_predicate.setForeground(get_color("color_predicate"))
  File "/Users/cchui/Documents/GitHub/macleod/macleod/gui/gui_beta/gui_highlighter.py", line 93, in get_color
    return QColor(filemgt.read_config("gui", setting_name, filemgt.config_file))
AttributeError: module 'macleod.Filemgt' has no attribute 'config_file'
`

(Screenshot enclosed below.)

Does gui_beta work with the changes that you've made?  Or should I try gui_alpha?  I have both Python 2.7.10 and Python 3.7.2 installed on this new machine.

![2019-03-12_17-00-08](https://user-images.githubusercontent.com/4117565/54235796-722a7f80-44e8-11e9-91fc-8847e95529b3.png)

**Comment by thahmann** [comment]
Transitioned to the new parser. gui beta should start up now again, though the check_consistency does not work from within the gui beta. For consistency checking, use check_consistency_new. There are also new translations to LADR and TPTP, all using clif_converter

**Comment by carmenchui** [comment]
Hi Torsten,
Thanks for the update -- I've tested it out on my new machine and gui_beta opens up again.  The new parser and translations with clif_converter are good as well.

I'll close this issue on GitHub since everything is working again.

Thanks,
Carmen

**Comment by carmenchui** [comment]
Hi Torsten,

Sorry to open this issue up again -- I wanted to update macleod on a computer I regularly use and came across this error after cloning the most recent commit (from March 15th 2019):

`AttributeError: module 'macleod' has no attribute 'Process'
`

Below is the log of the files that throw this error:
![2019-05-26_00-50-47](https://user-images.githubusercontent.com/4117565/58377513-6b8c9f80-7f50-11e9-95eb-4df564d51164.jpg)

I'm running:
- Mac OSX 10.10 Yosemite
- Python 3.5.4
- pyparsing 2.2.0
- ply 3.11
- texttable 1.6.1
- owlready 0.3.1
- PyQt5 5.10.1

**Comment by carmenchui** [comment]
Hi @thahmann,

Just an update on this... I figured out that it was an OS version issue since my two MacBooks are running different macOS versions (Yosemite macOS 10.10 and Mojave macOS 10.14.4).

PyQt5 is the culprit for some of the issues I came across when trying to run Macleod on my Yosemite Macbook since it has some Mac dependencies that require a higher macOS version before it can actually generate and display the Macleod GUI...

After some trial and error, I've determined the _minimum_ versions for the dependencies that appear to work with the latest commit (https://github.com/thahmann/macleod/commit/59e551af018e4a88274eabab64b36dd4b46817ca):
- pip3==19.0.2
- ply==3.11
- pyparsing==2.3.1
- configparser==3.7.3
- texttable==1.6.1
- owlready==0.3.1
- PyQt5==5.10

I think you should specify these versions in [macleod/setup.py](https://github.com/thahmann/macleod/blob/master/setup.py).

There is another error that I've come across with [macleod/macleod/Ontology.py](https://github.com/thahmann/macleod/blob/master/macleod/Ontology.py) but I'll create a separate GitHub issue for this.
