### ISSUE TITLE
translation for exists_at(x,t)

### ISSUE THREAD

**Issue by carmenchui** [thahmann/macleod#39]
In [psl_core.clif](http://colore.oor.net/psl_core/psl_core.clif), there is the following axiom:

`(forall (x occ t)
	(if	(participates_in x occ t)
		(and 	(exists_at x t)
         		(is_occurring_at occ t))))`

The latest commit to macleod will not translate this axiom due to the fact that `exists` is a keyword in the translation scripts.  It will not parse `exists_at` with the underscore -- even renaming to `existsAt` will cause the GUI to throw a token error:

> Error at line 129! Unexpected Token: '_̲at̲' 
> Error at line 151! Unexpected Token: '_̲at̲' 

![2019-07-11_13-01-38](https://user-images.githubusercontent.com/4117565/61070204-190e2200-a3dc-11e9-8940-8df481ff6873.jpg)

I would believe this error would be thrown if there are other relations with names that start with any of the quantifier keywords.

**Comment by Fxhnd** [comment]
Reworked the parser a bit so this shouldn't be an issue any more. Also fixed the issue where comments weren't allowed to be broken across newlines. Currently sitting at the head of the DL branch which has merged all of masters changes in so it should include the GUI. Still needs testing.
